### ISSUE TITLE
Failed to validate purchase both in demo website and in code i wrote

### ISSUE THREAD

**Issue by Kuoyhout** [voltrue2/in-app-purchase#104]
I try to validate a subscription receipt from Google Play which worked before but it's suddenly failed both in demo website and my code since yesterday. My app is in Alpha release state.

```
Public Key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkQx3UyWi4zBwuiTfDzufqYu6bIhz1yrbBG2BFz4hXTOJa7e7cMDC3ws/BBov16GFoCgBcTQB1eHQGAazGDKZydNez1SMxqLf3JMR6rFos2XBxYiOQ749xA4Aur7mlaleFMCERg4aUhvAUqIoaYEQp6Aajk6YySVF9q1kQHMVSwyJq26FwM3DUS0Gc0KDRUVoCGqseILxeMhzdKsrmTiRVh2CfigCfjrx8cLRKzcYgl/cHKNTGT/bzYQliwL7qoLuOXCXTKDlbUlWttYAckVMiSBTSaQtiIp5FYVRG59w93bfYzg+ohH23bpoUc4pzloCXr9amBhhryhJbMNLykA7ZwIDAQAB"

Receipt: {"data": {
"packageName":"com.wordpress.kuoyhuot.lookupdict",
"productId":"premium",
"purchaseTime":1499828057944,
"purchaseState":0,
"purchaseToken":"fpllagckfahcibjagdjkacga.AO-J1Ozi2KcpXVUMqso9lKkVIVJEWT_u3JWnc_7lrW7-tl9qQYb5yCKeNerf36-cVhZGfbJGXH5jbIVmhlJKBfNUIyxBCAQ-prl9H05lD9AooXR-vl1KHZVlNKOPjdMCmBECPEwiCn_y",
"autoRenewing":false
},"
signature":"YBytv5QcLENU3vgT6x2QHusNYyL9CluAGt6YIJ7JPxf+Za3nuuyIsjj2TnN9Hg0XDQ9g6zIPic0c9CNzojjE2I2bjCzJ/a+w2ttUkANrj3xMglVUw7Lrl6E30u8QXZJKrfS71ENtn4agAwn9qjy7IZFBlFUa5Y2IUTEkFj59cas/itmcF+c/djCMvVPlYHqiKQPPrLQ4mVZqVWK9ggeDhy6ULxufUrqGeX6P2w6BrcnbAevogxsoUTX3F9z95YFi5O+JzGwWbKE89OWNVXq4YraXxJXfYYW+fcRNB64qfwwvCFkSw3BrSGdm//4X26PogYz3A8+yMFVWrLKjadKLUg=="
}
```

And this is the log:

```
[VERBOSE] <Google> Failed against live public key: Error: failed to validate purchase
    at validatePublicKey (/user_code/node_modules/in-app-purchase/lib/google.js:438:5)
    at Object.module.exports.validatePurchase (/user_code/node_modules/in-app-purchase/lib/google.js:182:2)
    at Object.module.exports.validate (/user_code/node_modules/in-app-purchase/index.js:94:11)
    at /user_code/index.js:46:21
    at /user_code/node_modules/in-app-purchase/lib/async.js:60:5
    at Object.module.exports.setup (/user_code/node_modules/in-app-purchase/lib/amazon.js:50:10)
    at /user_code/node_modules/in-app-purchase/index.js:45:11
    at iterator (/user_code/node_modules/in-app-purchase/lib/async.js:54:3)
    at Object.module.exports.parallel (/user_code/node_modules/in-app-purchase/lib/async.js:65:3)
    at Object.module.exports.setup (/user_code/node_modules/in-app-purchase/index.js:37:8)

[VERBOSE] <Google> Failed against sandbox public key: Error: failed to validate purchase
    at validatePublicKey (/user_code/node_modules/in-app-purchase/lib/google.js:438:5)
    at /user_code/node_modules/in-app-purchase/lib/google.js:195:4
    at validatePublicKey (/user_code/node_modules/in-app-purchase/lib/google.js:438:2)
    at Object.module.exports.validatePurchase (/user_code/node_modules/in-app-purchase/lib/google.js:182:2)
    at Object.module.exports.validate (/user_code/node_modules/in-app-purchase/index.js:94:11)
    at /user_code/index.js:46:21
    at /user_code/node_modules/in-app-purchase/lib/async.js:60:5
    at Object.module.exports.setup (/user_code/node_modules/in-app-purchase/lib/amazon.js:50:10)
    at /user_code/node_modules/in-app-purchase/index.js:45:11
    at iterator (/user_code/node_modules/in-app-purchase/lib/async.js:54:3)

Error: failed to validate purchase
    at validatePublicKey (/user_code/node_modules/in-app-purchase/lib/google.js:438:5)
    at Object.module.exports.validatePurchase (/user_code/node_modules/in-app-purchase/lib/google.js:182:2)
    at Object.module.exports.validate (/user_code/node_modules/in-app-purchase/index.js:94:11)
    at /user_code/index.js:46:21
    at /user_code/node_modules/in-app-purchase/lib/async.js:60:5
    at Object.module.exports.setup (/user_code/node_modules/in-app-purchase/lib/amazon.js:50:10)
    at /user_code/node_modules/in-app-purchase/index.js:45:11
    at iterator (/user_code/node_modules/in-app-purchase/lib/async.js:54:3)
    at Object.module.exports.parallel (/user_code/node_modules/in-app-purchase/lib/async.js:65:3)
    at Object.module.exports.setup (/user_code/node_modules/in-app-purchase/index.js:37:8)
```

**Comment by bernhardwaidacher** [comment]
Any news on this? Having the same problem....

**Comment by voltrue2** [comment]
Hello,
I am still looking into this issue.
@Kuoyhout you mentioned that it was working before.
Could you give me more details on the state when it was working?

**Comment by voltrue2** [comment]
The error (failed to validate) suggests that the receipt does does not match the public key provided.
You may get this error if you have:
- wrong receipt for the public key
- changed receipt

**Comment by voltrue2** [comment]
Hello,

This issue maybe related to this here.
Would you have a look at it?
https://github.com/voltrue2/in-app-purchase/issues/113

**Comment by voltrue2** [comment]
Closing the issue as I have not received any response.
Please reopen this issue if you run into a problem.

Cheers
