### ISSUE TITLE
Apple `failed to validate purchase` when the service is down

### ISSUE THREAD

**Issue by ubershmekel** [voltrue2/in-app-purchase#107]
https://github.com/voltrue2/in-app-purchase/blob/develop/lib/apple.js#L294

The data was a buffer which after calling `data.toString()` you'd  get `<html><body><b>Http/1.1 Service Unavailable</b></body> </html>` perhaps this can be detected and a more appropriate "apple services seem temporarily down" error message would be useful?

**Comment by voltrue2** [comment]
Hello 
Thanks for reaching out. Yeah giving more meaningful information on error such as this would be a good idea.

**Comment by farhankhwaja** [comment]
Any Updates on this Issue?? Is there any workaround for this scenario?

**Comment by voltrue2** [comment]
Hello

I haven’t gotten around it yet. My apologies. I’m doing lots of catch-ups because of my work schedule. Will definitely let you know once I get to it which I hope will be soon.

Cheers

**Comment by anshul-kai** [comment]
This happens to me from time to time too. Would be nice to actually catch this and return gracefully. Below is the `error` output.

```
1 Error: failed to validate purchase
    at handleResponse (/home/app/bnirvana-server/node_modules/in-app-purchase/lib/apple.js:387:8)
    at done (/home/app/bnirvana-server/node_modules/in-app-purchase/lib/apple.js:235:9)
    at _finish (/home/app/bnirvana-server/node_modules/in-app-purchase/lib/async.js:129:9)
    at series (/home/app/bnirvana-server/node_modules/in-app-purchase/lib/async.js:105:16)
    at _onSeries (/home/app/bnirvana-server/node_modules/in-app-purchase/lib/async.js:124:5)
    at trySandbox (/home/app/bnirvana-server/node_modules/in-app-purchase/lib/apple.js:190:20)
    at series (/home/app/bnirvana-server/node_modules/in-app-purchase/lib/async.js:114:5)
    at _onSeries (/home/app/bnirvana-server/node_modules/in-app-purchase/lib/async.js:124:5)
    at /home/app/bnirvana-server/node_modules/in-app-purchase/lib/apple.js:184:13
    at Request._callback (/home/app/bnirvana-server/node_modules/in-app-purchase/lib/apple.js:398:16)
    at Request.self.callback (/home/app/bnirvana-server/node_modules/in-app-purchase/node_modules/request/request.js:185:22)
    at Request.emit (events.js:180:13)
    at Request.emit (domain.js:422:20)
    at Request.<anonymous> (/home/app/bnirvana-server/node_modules/in-app-purchase/node_modules/request/request.js:1157:10)
    at Request.emit (events.js:180:13)
    at Request.emit (domain.js:422:20)
    at IncomingMessage.<anonymous> (/home/app/bnirvana-server/node_modules/in-app-purchase/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.emit (events.js:185:15)
    at IncomingMessage.emit (domain.js:422:20)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)
```
