### ISSUE TITLE
Please update xml-crypto modules in dependencies

### ISSUE THREAD

**Issue by ionian-wind** [voltrue2/in-app-purchase#145]
I have an issue while trying to validate windows receipt
```
[1513594392040][VERBOSE] <Windows> Failed to validated: Error: canonicalization algorithm 'http://www.w3.org/TR/2001/REC-xml-c14n-20010315' is not supported
at SignedXml.findCanonicalizationAlgorithm (/home/user/***/node_modules/in-app-purchase/node_modules/xml-crypto/lib/signed-xml.js:288:14)
at SignedXml.getCanonXml (/home/user/***/node_modules/in-app-purchase/node_modules/xml-crypto/lib/signed-xml.js:595:26)
at SignedXml.validateSignatureValue (/home/user/***/node_modules/in-app-purchase/node_modules/xml-crypto/lib/signed-xml.js:271:30)
at SignedXml.checkSignature (/home/user/***/node_modules/in-app-purchase/node_modules/xml-crypto/lib/signed-xml.js:261:13)
at /home/user/***/node_modules/in-app-purchase/lib/windows.js:66:12
at Request._callback (/home/user/***/node_modules/in-app-purchase/lib/windows.js:133:3)
at Request.self.callback (/home/user/***/node_modules/in-app-purchase/node_modules/request/request.js:186:22)
at emitTwo (events.js:125:13)
at Request.emit (events.js:213:7)
at Request.<anonymous> (/home/user/***/node_modules/in-app-purchase/node_modules/request/request.js:1163:10)
```
This behavior already fixed in newer version of xml-crypto module
Related issue in xml-crypto https://github.com/yaronn/xml-crypto/issues/68

**Comment by voltrue2** [comment]
Hello,
I apologize for the late response on this.
It seems one of the tests on CI is failing. 
I will look into this.

Cheers

**Comment by voltrue2** [comment]
640104ab0db7ea8673464a0a99db7808a483c87e
