### ISSUE TITLE
Error: read ECONNRESET when validate receipt apple

### ISSUE THREAD

**Issue by ntlzz93** [voltrue2/in-app-purchase#155]
Log from my debugging
validate fail at 
```
**at /home/money-sync/ml-sync-test-revo/node_modules/in-app-purchase/lib/async.js:96:11
at /home/money-sync/ml-sync-test-revo/node_modules/in-app-purchase/lib/apple.js:169:12**

 **at self.callback (/home/money-sync/ml-sync-test-revo/node_modules/in-app-purchase/node_modules/request/request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/home/money-sync/ml-sync-test-revo/node_modules/in-app-purchase/node_modules/request/request.js:884:8)**
```

```
debug:purchase-api serviceKey  +3ms APPLE
  debug:purchase-api exception  +2m { Error: Unknown Error
    at MoneyError (/home/money-sync/ml-sync-test-revo/dist/exception/MoneyError.js:15:9)
    at UnknownError (/home/money-sync/ml-sync-test-revo/dist/exception/UnknownError.js:15:9)
    at _inAppPurchase2.default.validate (/home/money-sync/ml-sync-test-revo/dist/router/api/purchase.js:185:33)
    at done (/home/money-sync/ml-sync-test-revo/node_modules/in-app-purchase/lib/apple.js:193:11)
    at /home/money-sync/ml-sync-test-revo/node_modules/in-app-purchase/lib/async.js:96:11
    at /home/money-sync/ml-sync-test-revo/node_modules/in-app-purchase/lib/apple.js:169:12
    at Request._callback (/home/money-sync/ml-sync-test-revo/node_modules/in-app-purchase/lib/apple.js:323:10)
    at self.callback (/home/money-sync/ml-sync-test-revo/node_modules/in-app-purchase/node_modules/request/request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/home/money-sync/ml-sync-test-revo/node_modules/in-app-purchase/node_modules/request/request.js:884:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
  errorCode: 204,
  message: 'Unknown Error',
  detail: 'Error: read ECONNRESET' }
```

Please help

**Comment by voltrue2** [comment]
Hello 

It seems you have a network error. I do not believe it is related to in-app-purchase library though.

Cheers
