### ISSUE TITLE
Google Service Account - Error when Validating

### ISSUE THREAD

**Issue by cnmongrel** [voltrue2/in-app-purchase#214]
I am receiving the following error when attempting to validate with the Google Service Account setup -

Error:
```
Error: {"error":"invalid_request","error_description":"Incorrect header: Content-Type"}
    at Request._callback (/Users/user/Projects/repos-git/iap-validate/node_modules/in-app-purchase/lib/googleAPI.js:158:23)
    at Request.self.callback (/Users/user/Projects/repos-git/iap-validate/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/Users/user/Projects/repos-git/iap-validate/node_modules/request/request.js:1157:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/Users/user/Projects/repos-git/iap-validate/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Here is the code (Keys and other sensitive info sanitized):
```javascript
var iap = require('in-app-purchase');

iap.config({
    googleServiceAccount: {
        clientEmail: 'iap-validate@api-project-0123456789.iam.gserviceaccount.com',
        privateKey: '-----BEGIN PRIVATE KEY-----\nXXXXXXXXXXXXXXXXXXXX\n-----END PRIVATE KEY-----\n'
    }
});

var receipt = {
    packageName: 'com.company.app',
    productId: 'com.company.app.thing',
    purchaseToken: 'doijjdaXXXXXXX'
};

iap.setup(function (error) {
    if (error) {
        console.error(error);
    }
    iap.validate(receipt, function (error, response) {
        if (error) {
            // Failed to validate
            console.error(error);
        }
        if (iap.isValidated(response)) {
            // Succuessful validation
            console.log(response);
        }
    });
});
```

The service account has been granted read access to Financial data in the Google Developer Console.

I appreciate any insight as to what is causing the error. Thanks!

**Comment by voltrue2** [comment]
Hello

Thank you for reporting this issue. I haven’t seen this error before but according to the error discription, we are somehow sending the wrong value for the header content-type.
I believe the correct value for it is “application/x-www-form-urlencoded” which is standard. 
Would you mind checking if the request sent from the library has the correct request headers?
I will test on my end also in the meantime.

Cheers!

**Comment by voltrue2** [comment]
Hello,

I think I found an issue in my library. I think I have fix in my develop branch.
Would you mind trying it out and see if this fixes your problem?

Cheers!

**Comment by cnmongrel** [comment]
Hi, Thanks for the quick response!

I updated the `googleAPI.js` file with your changes from the develop branch. Now I'm getting the following error:
```
Error: Status:401 - {
  "error": {
    "errors": [
      {
        "domain": "global",
        "reason": "required",
        "message": "Login Required",
        "locationType": "header",
        "location": "Authorization"
      }
    ],
    "code": 401,
    "message": "Login Required"
  }
}
    at Request._callback (/Users/jariggall/Projects/repos-git/cartoon-iap-validate/node_modules/in-app-purchase/lib/googleAPI.js:112:27)
    at Request.self.callback (/Users/jariggall/Projects/repos-git/cartoon-iap-validate/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/Users/jariggall/Projects/repos-git/cartoon-iap-validate/node_modules/request/request.js:1157:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/Users/jariggall/Projects/repos-git/cartoon-iap-validate/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Thanks for diving into this!

**Comment by voltrue2** [comment]
Hello,

Let me have a look at it again. Thank you for your patience.

Cheers!

**Comment by cnmongrel** [comment]
Thanks @voltrue2, let me know if you need any other info from my side.

**Comment by ghsdh3409** [comment]
@cnmongrel @voltrue2 
I make pull request #215 to fix this issue. Could you check again if it works?

**Comment by cnmongrel** [comment]
@ghsdh3409 @voltrue2 
I added the `json: true` change from @ghsdh3409's PR to the `googleAPI.js` and it's now working. Thanks guys for the fixes!

**Comment by voltrue2** [comment]
@ghsdh3409 @cnmongrel
  

  
Thank you guys so much for the help! I will make the proper monarch with   @ghsdh3409’s PR and publish the fixed version on non ASAP!
  
  
  
 Cheers to both!
  

  
  

  
  
>

**Comment by cnmongrel** [comment]
Hi @voltrue2, when do you expect the fix to be available via NPM?

**Comment by voltrue2** [comment]
Hello
  

  
I am hoping to do this within a few days. My another project (a paying project) is getting really close to a launch so I’m kind of in a crunch mode, but I will be getting back to this very soon.
  

  
Cheers!
  

  

  
  

  
  
>

**Comment by cnmongrel** [comment]
Awesome, thanks @voltrue2!
