### ISSUE TITLE
doc.firstChild.getAttribute is not a function - Windows

### ISSUE THREAD

**Issue by githubowl** [voltrue2/in-app-purchase#232]
Hello there,

I am trying to validate a windows store receipt which seems to be properly formed xml, but I am getting the error:

 <Windows> Failed: TypeError: doc.firstChild.getAttribute is not a function

Could you tell me where I should look please?

Thank you

**Comment by voltrue2** [comment]
Hello
  

  
Would you please send me the stack trace of the error?
  

  
Cheers
  

  
  

  
  
>

**Comment by githubowl** [comment]
Hello there,

thank you for responding so quick.

The trace is:

$
[1545325364606][VERBOSE] <Windows> Failed: TypeError: doc.firstChild.getAttribute is not a function
    at Object.module.exports.validatePurchase (/root/mediaplaylist/node_modules/in-app-purchase/lib/windows.js:43:33)
    at Object.module.exports.validate (/root/mediaplaylist/node_modules/in-app-purchase/index.js:146:21)
    at /root/mediaplaylist/node_modules/in-app-purchase/index.js:125:28
    at Object.module.exports.validate (/root/mediaplaylist/node_modules/in-app-purchase/index.js:124:16)
    at iap.setup.then (/util/index.js:1325:21)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)

my code:
        iap.setup()
            .then(() => {
                // iap.validate(...) automatically detects what type of receipt you are trying to validate
                iap.validate(receipt).then(onSuccess).catch(onError);
            })
            .catch((error) => {
                console.log('error1:' + JSON.stringify(error));
            });

Thanks again.

**Comment by githubowl** [comment]
Hello there,
thank you for responding so quick.
The trace is:
$
[1545325364606][VERBOSE] Failed: TypeError: doc.firstChild.getAttribute is not a function
at Object.module.exports.validatePurchase (/code/node_modules/in-app-purchase/lib/windows.js:43:33)
at Object.module.exports.validate (/code/node_modules/in-app-purchase/index.js:146:21)
at /code/node_modules/in-app-purchase/index.js:125:28
at Object.module.exports.validate (/code/node_modules/in-app-purchase/index.js:124:16)
at iap.setup.then (/util/index.js:1325:21)
at process._tickDomainCallback (internal/process/next_tick.js:129:7)
my code:
iap.setup()
.then(() => {
// iap.validate(...) automatically detects what type of receipt you are trying to validate
iap.validate(receipt).then(onSuccess).catch(onError);
})
.catch((error) => {
console.log('error1:' + JSON.stringify(error));
});
Thanks again.

**Comment by githubowl** [comment]
I have found the problem. My xml had <?xml version="1.0"?> as a header which caused it to fail. When I strip that off, it works.

**Comment by voltrue2** [comment]
Great! Thank you for reporting back
