### ISSUE TITLE
bad base64 decode

### ISSUE THREAD

**Issue by ksabariraj** [voltrue2/in-app-purchase#235]
Good Day,

I generated google public key as mentioned in the document. But, I am getting "error:0906D064:PEM routines:PEM_read_bio:bad base64 decode" error. Could you please help me on this?

> Error: error:0906D064:PEM routines:PEM_read_bio:bad base64 decode
    at Verify.verify (crypto.js:381:23)
    at validatePublicKey (/app/node_modules/in-app-purchase/lib/google.js:794:27)
    at validateMethod (/app/node_modules/in-app-purchase/lib/google.js:250:13)
    at Object.module.exports.validatePurchase (/app/node_modules/in-app-purchase/lib/google.js:282:5)
    at Object.module.exports.validate (/app/node_modules/in-app-purchase/index.js:143:20)
    at /app/index.js:23:9
    at _finish (/app/node_modules/in-app-purchase/lib/async.js:129:9)
    at series (/app/node_modules/in-app-purchase/lib/async.js:105:16)
    at _onSeries (/app/node_modules/in-app-purchase/lib/async.js:124:5)
    at Object.module.exports.setup (/app/node_modules/in-app-purchase/lib/amazon.js:54:16)
{ status: 1,
  message: 'error:0906D064:PEM routines:PEM_read_bio:bad base64 decode' }

Thanks,
Sabari.

**Comment by voltrue2** [comment]
Hello, 
This means that your public key is incorrect.
You will need to use the correct public key that you get from Google Play developer account.

Cheers

**Comment by ksabariraj** [comment]
Thanks for your reply.

After getting the access token do we need to do any encoding? Please see the below image. I'm using the access token data for the API. 

FYI, I try tried to decode/encode the access token in base64. But, got bad data error.

![screen shot 2019-01-10 at 9 19 31 am](https://user-images.githubusercontent.com/3765085/50945109-3871d400-14b9-11e9-98a4-8964509c4ede.jpg)

THanks,
Sabari.

**Comment by voltrue2** [comment]
Hello,

Here is the steps you can take: https://github.com/voltrue2/in-app-purchase#google-play-store-api
