### ISSUE TITLE
async.waterfall is not a function

### ISSUE THREAD

**Issue by calendee** [voltrue2/in-app-purchase#44]
When using the Google validation process, receive get this error:

```
TypeError: async.waterfall is not a function
    at checkSubscriptionStatus (/mnt/app/node_modules/in-app-purchase/lib/google.js:286:8)
    at /mnt/app/node_modules/in-app-purchase/lib/google.js:157:3
    at validatePublicKey (/mnt/app/node_modules/in-app-purchase/lib/google.js:315:10)
    at module.exports.validatePurchase (/mnt/app/node_modules/in-app-purchase/lib/google.js:139:2)
    at Object.module.exports.validate (/mnt/app/node_modules/in-app-purchase/index.js:53:2)
    at /mnt/app/index.js:664:21
    at /mnt/app/node_modules/in-app-purchase/lib/async.js:60:5
    at Object.module.exports.setup (/mnt/app/node_modules/in-app-purchase/lib/amazon.js:43:10)
    at /mnt/app/node_modules/in-app-purchase/index.js:30:11
    at iterator (/mnt/app/node_modules/in-app-purchase/lib/async.js:54:3)
```

This seems to be because the `async` library is not actually used.  Instead a custom `async` file is used that does not have the waterfall method.

Here is the problem code at Line 286 of `google.js`:

```
async.waterfall(tasks, done);
```

The custom `async` module at https://github.com/voltrue2/in-app-purchase/blob/develop/lib/async.js does not have a method named `waterfall`.

**Comment by voltrue2** [comment]
Hello

Thank you for reporting the issue.
I will look into this ASAP.

Best

**Comment by voltrue2** [comment]
Hello

I appreciate you taking the time to report this issue.
I have made the fix and updated the package.
Please have a look at v1.0.3

Best Regards

**Comment by calendee** [comment]
Worked great.  Thanks so much for the amazingly fast response and fix.

**Comment by voltrue2** [comment]
Thank you for reaching out!
